name: check for new accounts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 1"
jobs:
  check-exodus:
    runs-on: ubuntu-latest
    steps:
      - name: Check Twitter list for Maston accounts
        id: export
        uses: potatoqualitee/exodus@v1.1
        with:
          list-members: "1590287371320233986"
          include-private: true
        env:
          BLUEBIRDPS_API_KEY: "${{ secrets.BLUEBIRDPS_API_KEY }}"
          BLUEBIRDPS_API_SECRET: "${{ secrets.BLUEBIRDPS_API_SECRET }}"
          BLUEBIRDPS_ACCESS_TOKEN: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN }}"
          BLUEBIRDPS_ACCESS_TOKEN_SECRET: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN_SECRET }}"
          BLUEBIRDPS_BEARER_TOKEN: "${{ secrets.BLUEBIRDPS_BEARER_TOKEN }}"
      - name: Import the results
        uses: potatoqualitee/influx@v1
        id: import
        with:
          server: fosstodon.org
          file-path: ${{ steps.export.outputs.mastodon-csv-filepath }}
        env:
          ACCESS_TOKEN: "${{ secrets.FOSSTODON_TOKEN }}"
