name: Update Twitter List
on:
  workflow_dispatch:
  schedule:
    # Time is in UTC. 9am PST on Mondays.
    - cron: "0 17 * * 1"
jobs:
  synctotwitter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: BluebirdPS
      - name: Sync to Twitter
        shell: pwsh
        env:
          BLUEBIRDPS_API_KEY: "${{ secrets.BLUEBIRDPS_API_KEY }}"
          BLUEBIRDPS_API_SECRET: "${{ secrets.BLUEBIRDPS_API_SECRET }}"
          BLUEBIRDPS_ACCESS_TOKEN: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN }}"
          BLUEBIRDPS_ACCESS_TOKEN_SECRET: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN_SECRET }}"
          BLUEBIRDPS_BEARER_TOKEN: "${{ secrets.BLUEBIRDPS_BEARER_TOKEN }}"
        run: ./sync.ps1
